name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  # clone-repo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
  #     - name: List files in the repository
  #       run: |
  #         ls ${{ github.workspace }}
  #     - run: echo "🍏 This job's status is ${{ job.status }}."
  docker-build:
    runs-on: [mohab-virtual-machine]
    permissions:
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mohabrabie/node-app:latest
      - run: echo $'\e[7mmohabrabie/node-app:latest\e[0m built and pushed 🚀'

  build-notifications:
      needs: docker-build
      runs-on: ubuntu-latest
      steps:
      - name: Send Push Notification
        uses: techulus/push-github-action@1.0.0
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MESSAGE: "mohabrabie/node-app:latest created and pushed to docker hub 🚀"

  docker-deploy:
    needs: build-notifications
    runs-on: ubuntu-latest
    steps:
      - name: running a docker container
        run: docker run -dp 127.0.0.1:3000:3000 mohabrabie/node-app:latest

      - name: check the running container
        run: docker ps
  
  deploy-notifications:
    needs: docker-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MESSAGE: "mohabrabie/node-app:latest Deployed!"
